version: "2.1"
services:

  kong-database:
    image: postgres:latest
    container_name: kong-database
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_PASSWORD=kong
      - POSTGRES_DB=kong
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kong"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      soa-twitter:
        ipv4_address: 10.3.0.16

  kong:
    build: ./kong
    container_name: kong
    command: sh run.sh
    depends_on:
      kong-database:
        condition: service_healthy
    restart: always
    ports:
      - 8000:8000
      - 8443:8443
      - 8001:8001
      - 8444:8444
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=10.3.0.16
      - KONG_PG_DATABASE=kong
      - KONG_PG_USER=kong
      - KONG_PG_PASSWORD=kong
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - KONG_DNS_RESOLVER=10.3.0.15:8600
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
    networks:
      soa-twitter:
        ipv4_address: 10.3.0.17

  consul:
    image: consul:latest
    container_name: consul
    depends_on:
      kong-database:
        condition: service_healthy
    volumes:
      - ./consul/kong-database.json:/consul/config/kong-database.json
    ports:
      - '8300:8300'
      - '8301:8301'
      - '8301:8301/udp'
      - '8500:8500'
      - '8600:8600'
      - '8600:8600/udp'
    networks:
      soa-twitter:
        ipv4_address: 10.3.0.15

  users_database:
    image: postgres:latest
    restart: always
    container_name: users_database
    ports: 
     - "5434:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=users
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      soa-twitter:
        ipv4_address: 10.3.0.33

  tweets_database:
    image: postgres:latest
    restart: always
    container_name: tweets_database
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=tweets
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      soa-twitter:
        ipv4_address: 10.3.0.32

  tweets:
    build: ./tweets
    container_name: microservice_tweets
    command: gunicorn --workers=1 -b :10001 app:app
    depends_on:
      - consul
      - tweets_database
    ports:
      - 10001:10001
    environment:
      - CONSUL_HOST=10.3.0.15
      - CONSUL_PORT=8500
      - SERVICE_PORT=10001
      - SERVICE_IP=10.3.0.22
      - APP_SETTINGS=config.ProductionConfig
      - DATABASE_URL=postgresql://postgres:admin@10.3.0.32/tweets
    networks:
      soa-twitter:
        ipv4_address: 10.3.0.22

  users:
    build: ./users
    container_name: microservice_users
    command: gunicorn --workers=1 -b :10002 app:app
    depends_on:
      - consul
      - users_database
    ports:
      - 10002:10002
    environment:
      - CONSUL_HOST=10.3.0.15
      - CONSUL_PORT=8500
      - SERVICE_PORT=10002
      - SERVICE_IP=10.3.0.23
      - APP_SETTINGS=config.ProductionConfig
      - DATABASE_URL=postgresql://postgres:admin@10.3.0.33/users
      - KONG_HOST=10.3.0.17
      - KONG_PORT=8001
    networks:
      soa-twitter:
        ipv4_address: 10.3.0.23

  follows:
    build: ./follows
    container_name: microservice_follows
    command: gunicorn --workers=1 -b :10003 app:app
    depends_on:
      - consul
    ports:
      - 10003:10003
    environment:
      - CONSUL_HOST=10.3.0.15
      - CONSUL_PORT=8500
      - SERVICE_PORT=10003
      - SERVICE_IP=10.3.0.24
    networks:
      soa-twitter:
        ipv4_address: 10.3.0.24

  favorites:
    build: ./favorites
    container_name: microservice_favorites
    command: gunicorn --workers=1 -b :10004 app:app
    depends_on:
      - consul
    ports:
      - 10004:10004
    environment:
      - CONSUL_HOST=10.3.0.15
      - CONSUL_PORT=8500
      - SERVICE_PORT=10004
      - SERVICE_IP=10.3.0.25
    networks:
      soa-twitter:
        ipv4_address: 10.3.0.25

networks:
  soa-twitter:
    driver: bridge
    ipam:
      config:
        - subnet: 10.3.0.0/16
          gateway: 10.3.0.1